# SPDX-License-Identifier: MPL-2.0
"""Derive paragraph styles with changed spacing, and prove which styles we derived."""

from __future__ import annotations

import copy
from typing import TYPE_CHECKING

from lxml import etree

from odfa11y.odf import NS, qn

from .style_properties import SPACING_ATTRIBUTES, attr_from_display

if TYPE_CHECKING:
    from .styles import StyleCatalog


def derive_paragraph_style(
    catalog: StyleCatalog,
    base_style_name: str | None,
    new_style_name: str,
    spacing: dict[str, str],
) -> etree._Element:
    """Build, without inserting it, a style equal to a base but with given spacing.

    Returns
    -------
    etree._Element
        A detached paragraph style named ``new_style_name``.

    """
    base = catalog.style("paragraph", base_style_name)
    if base is not None:
        derived = copy.deepcopy(base)
    else:
        derived = etree.Element(qn("style", "style"))
        if base_style_name:
            derived.set(qn("style", "parent-style-name"), base_style_name)
    derived.set(qn("style", "name"), new_style_name)
    derived.set(qn("style", "family"), "paragraph")
    set_spacing(derived, spacing)
    return derived


def is_generated_from(
    catalog: StyleCatalog,
    existing: etree._Element,
    base_style_name: str | None,
    new_style_name: str,
) -> bool:
    """Whether a style is, apart from its spacing, exactly what we would derive.

    Only a style that lives among the automatic styles of the content part and equals the
    derivation of ``base_style_name`` in everything but spacing counts as generated by us;
    any other style of the same name belongs to someone else.

    Returns
    -------
    bool
        True when ``existing`` can be proven to be our own earlier output.

    """
    parent = existing.getparent()
    if parent is None or parent.tag != qn("office", "automatic-styles"):
        return False
    if parent.getroottree().getroot() is not catalog.content_tree.getroot():
        return False
    expected = derive_paragraph_style(catalog, base_style_name, new_style_name, {})
    return _canonical(existing) == _canonical(expected)


def adopt_style(catalog: StyleCatalog, style: etree._Element) -> None:
    """Insert a derived style among the content part's automatic styles and index it."""
    auto_styles = catalog.content_tree.find("office:automatic-styles", NS)
    if auto_styles is None:
        root = catalog.content_tree.getroot()
        auto_styles = etree.Element(qn("office", "automatic-styles"))
        body = root.find("office:body", NS)
        insert_at = root.index(body) if body is not None else len(root)
        root.insert(insert_at, auto_styles)
    auto_styles.append(style)
    catalog.register("paragraph", style)


def set_spacing(style: etree._Element, spacing: dict[str, str]) -> None:
    """Replace the spacing attributes a style declares itself."""
    props = style.find(qn("style", "paragraph-properties"))
    if props is None:
        props = etree.SubElement(style, qn("style", "paragraph-properties"))
    for key in SPACING_ATTRIBUTES:
        props.attrib.pop(key, None)
    for display_name, value in spacing.items():
        key = attr_from_display(display_name)
        if key in SPACING_ATTRIBUTES:
            props.set(key, value)


def _canonical(style: etree._Element) -> bytes:
    """Serialize a style without its spacing attributes, for equivalence checks.

    Returns
    -------
    bytes
        Canonical XML of a copy that carries no spacing.

    """
    clone = copy.deepcopy(style)
    props = clone.find(qn("style", "paragraph-properties"))
    if props is not None:
        for key in SPACING_ATTRIBUTES:
            props.attrib.pop(key, None)
    return etree.tostring(clone, method="c14n", exclusive=True)
